name: qr_flutter
description: >
  QR.Flutter is a Flutter library for simple and fast QR code rendering via a
  Widget or custom painter.
version: 3.2.0
homepage: https://github.com/lukef/qr.flutter

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.7.0"

dependencies:
  flutter:
    sdk: flutter
  qr:
    git:
      url: https://github.com/wq1977/qr.dart.git
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.6.0

flutter:
  uses-material-design: false
